# Generated by Django 5.1.6 on 2025-02-16 22:32

import django.core.validators
import sistema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='Producto',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, validators=[sistema.models.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.')]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(validators=[sistema.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(validators=[sistema.models.validar_precio]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(validators=[sistema.models.validar_precio]),
        ),
    ]
