# Generated by Django 5.1.6 on 2025-02-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_factura_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='producto',
            new_name='menu',
        ),
    ]
